yakworks/angle-grinder

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/angleGrinder/modules/forms/panels.coffee
Added ability to leave first row of the collapsed grid if there is no highlighted
> Added ability to leave first row of the collapsed grid

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/notificationDialog.coffee
- tests/unit/angleGrinder/common/notificationDialogSpec.coffee
>  make it possible to specify label ok button on notification dialog

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.alerts.min.js
- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/massUpdateHandler.coffee
- src/scripts/utils/alerts.coffee
- tests/unit/angleGrinder/forms/massUpdateHandlerSpec.coffee
> Display mass update errors

- grails/ag-plugin/src/groovy/grinder/Pager.groovy
- grails/ag-plugin/test/unit/grinder/PagerSpec.groovy
9ci/rcm#1599 - Add eachPage method to Pager
> 9ci/rcm#1599 - Add eachPage method to Pager

- grails/ag-plugin/web-app/angleGrinder/js/application.js
> Display status code and url in error message

- grails/ag-plugin/web-app/angleGrinder/js/application.js
> Display status text in error message if available

- grails/ag-plugin/web-app/angleGrinder/scripts/angular-mocks.min.js
- src/index.html
> Added angular mocks to plugin rel rcm#1668

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/agGridCtrl.coffee
> Added ability highlight grid row 0.6x

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/agGridPlaceholder.coffee
> Fixed assets disappearing on route changes 9ci/rcm#1762

- grails/ag-plugin/web-app/angleGrinder/scripts/gridz.min.js
- src/scripts/gridz/gridz.coffee
> Changed selection behaviour rcm/#1764

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/forms.coffee
- src/scripts/forms/panels.coffee
Closes 9ci/rcm#1825
Closes 9ci/rcm#1826
> Changed using of uib tooltips

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/index.html
- src/scripts/gridz/agNewButton.coffee
- src/scripts/gridz/agReloadGrid.coffee
- src/scripts/gridz/excelExport.coffee
> Changes for toolbars styling rel rcm#1788

- grails/ag-plugin/web-app/angleGrinder/js/modules/resources.js
- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- grunt-tasks/config/copy.coffee
- src/index.html
- src/scripts/common/common.coffee
- src/scripts/common/deepDiff.coffee
- src/scripts/common/restrictResource.coffee
- tests/karma-files.coffee
- tests/unit/angleGrinder/common/deepDiffSpec.coffee
- tests/unit/angleGrinder/common/restrictResourceSpec.coffee
> Restrict resource json rel 9ci/rcm#1770

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/agSubmitButton.coffee
- tests/unit/angleGrinder/forms/sumitButtonSpec.coffee
> Disable submit button while modal closing 9ci/rcm#1879

- grails/ag-plugin/web-app/angleGrinder/scripts/gridz.min.js
- src/scripts/gridz/gridz.coffee
> ColModel align has higher priority then formaters aligning 

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/common/deepDiff.coffee
- src/scripts/common/restrictResource.coffee
- src/scripts/gridz/gridCrudCtrl.coffee
> Restrict json for angular 1.4 rel 9ci/rcm#1770

- grails/ag-plugin/src/groovy/grinder/MapFlattener.groovy
- grails/ag-plugin/test/unit/grinder/MapFlattenerTest.groovy
> 2059 fix mapflatter

- grails/ag-plugin/grails-app/services/grinder/GrinderLabelService.groovy
- grails/ag-plugin/src/groovy/grinder/MapFlattener.groovy
- grails/ag-plugin/src/groovy/grinder/Pager.groovy
- grails/ag-plugin/test/unit/grinder/BeanPathToolsSpec.groovy
- grails/ag-plugin/test/unit/grinder/GrinderLabelServiceTests.groovy
- grails/ag-plugin/test/unit/grinder/MapFlattenerTest.groovy
> 2062 fix tests

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSubmit.coffee
- tests/unit/angleGrinder/forms/agSubmitSpec.coffee
> Fixed issue with 'too much recursion' when trying to save nested form

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/services/FormDialogServ.coffee
> #2141 - Provide ability to expose record to parent scope

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/agGridz.coffee
> 9ci/rcm#2187 - Fix grid is not displayed when inside tab

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/index.html
- src/scripts/common/percentageFilter.coffee
> Add percentage filter

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/services/ConfirmationDialogServ.coffee
> 9ci/rcm#2144 - Add ability to pass option ''closeOnConfirm'

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSubmitButton.coffee
> Added ability to change text for submit button rel 9ci/rcm#2212

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelectBind.coffee
> Updated ag-select-bind to make it work when id is string

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Updated clicover configuration to make grid popup close on every click

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/gridCrud.coffee
- tests/unit/angleGrinder/gridz/gridCrudCtrlSpec.coffee
> Fixed focus for grid crud double click

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/gridCrud.coffee
> Select text in input on gridCrud dbl click rel 9ci/rcm#2282

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> Fixed issue with tag input redirecting on tag close

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/services/ConfirmationDialogServ.coffee
> 9ci/rcm#2341 - Always resolve promise with true or false

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/services/MassUpdateMixin.coffee
> Check if there is selected rows before massUpdate

- grails/ag-demo/application.properties
- grails/ag-demo/grails-app/conf/BuildConfig.groovy
- grails/ag-demo/grails-app/conf/DataSource.groovy
- grails/ag-demo/test/unit/grinder/OrgControllerTests.groovy
- grails/ag-plugin/application.properties
- grails/ag-plugin/grails-app/conf/BuildConfig.groovy
- grails/ag-plugin/grails-app/conf/DataSource.groovy
- grails/ag-plugin/grails-app/services/grinder/GrinderLabelService.groovy
- grails/ag-plugin/src/groovy/grinder/Pager.groovy
> 2426 grails255 upgrade

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Added abiluty to sort by several columns 9ci/rcm#2450

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/agGridz.coffee
- src/scripts/gridz/directives/agGridXlsExport.coffee
- tests/unit/angleGrinder/gridz/agGridzSpec.coffee
- tests/unit/angleGrinder/gridz/excelExportSpec.coffee
> 9ci/rcm#2482 - make export to excel generic

- src/scripts/gridz/directives/agGrid/gridz.coffee
> Added some comments rel 9ci/rcm#2450

- grails/ag-plugin/web-app/angleGrinder/js/application.js
- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/services/DialogCrudCtrlMixin.coffee
> 9ci/rcm#2465 - handle error while delete and show an alert

- grails/ag-plugin/web-app/angleGrinder/js/application.js
- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/validations.coffee
> 2573 validations

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/validations.coffee
- tests/unit/angleGrinder/forms/validationsSpec.coffee
> 9ci/rcm#2569 Fix agLength validator to not to consider empty fields

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> 9ci/rcm#2609 - Add tag when the input loose the focus

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/services/MassUpdateHandler.coffee
> Added mass update sucsess message 9ci/rcm#2670

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agNumber.coffee
> Ag-number directive return number not string rel 9ci/rcm#2838

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- grails/ag-plugin/web-app/angleGrinder/scripts/gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Grid enhancement

- Gruntfile.coffee
- README.md
- grunt-tasks/config/clean.coffee
> Update grunt clean commands #348

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/datepicker.coffee
> Fixed datepicker to be able delete date rel 9ci/rcm#3032

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/percentageFilter.coffee
> Fixed percentage filter

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/addEmptyOption.coffee
> Fixed issue with adding empty option to select rel 9ci/rcm#3169

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/gridCrud.coffee
> Add a possibility to focus select inputs in the edit form (rcm#3311)

- grails/ag-plugin/src/groovy/grinder/BeanPathTools.groovy
- grails/ag-plugin/src/groovy/grinder/MapFlattener.groovy
closes 9ci/rcm#2428 
@jdabal dont close it yet, i will let u know once i hve PR for each plugin
> Grails3 prep: remove legacy databinder

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/agGridCtrl.coffee
- src/scripts/gridz/directives/agGrid/agGridz.coffee
> Added ability to add additional footer to grid

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelect.coffee
> Added fillAll button for agSelect

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelect.coffee
> Added agSelect2Fill directive

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelect.coffee
> Added multiple config for agSelect

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelect.coffee
> Use multiple values by default

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agTabs.coffee
Remove container class for ag-tabs
> Remove container class for ag-tabs

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/agSelect.coffee
> Added clear functionality for select fill all button

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/agGridCtrl.coffee
> Moved additional footer to the bottom

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Added ability to add grid popover rel 9ci/rcm#3323

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
- src/scripts/gridz/services/ActionPopupHandler.coffee
> Add massUpdate option to action menu (3516)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/gridCrud.coffee
> Fix an issue with 'id' selector (3516)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/gridPagerCtrlMixin.coffee
> Add some changes to grid pager 9ci/rcm#3539

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGridQuickSearch.coffee
> Add a possibility to apply custom placeholder (3544)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/directives/editableDatepicker.coffee
- src/scripts/forms/directives/editableDirectiveFactory.coffee
> Fix an issue with datepicker at ArBatch edit form (3649)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/index.html
- src/scripts/gridz/directives/agResetSortGrid.coffee
> Add a possibility to reset sorting a grid (3511)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Add a possibility to select multiple sets of records (3664)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
> Fix an issue with a blank grid (3686)

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/gridCrud.coffee
> Added functionality for navigating in grid with arrows keys 9ci/rcm#3830

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
- src/scripts/gridz/directives/gridCrud.coffee
> Added ability to disable grid editing 9ci/rcm#4030

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/search.coffee
> Added ability to run method before advanced search 9ci/rcm#4125

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/agGridQuickSearch.coffee
> QuickSearch remove comma 9ci/rcm#4140

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> Fixed tag input group adding with spaces rel 9ci/rcm#2213

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> If first character is dot do not split into tags rel 9ci/rcm#4325

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> Spit into tags for + too rel 9ci/rcm#4325

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.common.min.js
- src/scripts/common/directives/tagInput.coffee
> Fixed tagInput rel 9ci/rcm#4325

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGridXlsExport.coffee
> Fixed number formatting on excel export rel 9ci/rcm#4349

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGridXlsExport.coffee
> Excel export column order rel 9ci/rcm#4367

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/agGridCtrl.coffee
- src/scripts/gridz/directives/agGridXlsExport.coffee
> Excel export row order rel 9ci/rcm#4370

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGrid/gridz.coffee
- src/scripts/gridz/directives/agGridXlsExport.coffee
- src/scripts/gridz/services/ApplyFormattersServ.coffee
> Excel export hide hidden columns rel 9ci/rcm#4370

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.forms.min.js
- src/scripts/forms/services/MassUpdateMixin.coffee
> Added ability to specify modal classes for massUpdateMixin 9ci/rcm#4423

- README.md
- src/scripts/common/agDateFilter.js
- src/scripts/forms/directives/datepicker.js
- src/scripts/select2/agSelect.js
- src/scripts/select2/ui.select2.js
- tests/karma.conf.js
- tests/unit/angleGrinder/common/agDateFilterSpec.js
- tests/unit/angleGrinder/forms/datepickerSpec.js
- tests/unit/angleGrinder/gridz/agGridCtrlSpec.js
- tests/unit/angleGrinder/gridz/agGridzSpec.js
- tests/unit/angleGrinder/gridz/gridCrudCtrlSpec.js
- tests/unit/angleGrinder/select2/uiSelect2Spec.js
- tests/unit/helpers/compileTemplate.js
> Fixing tests start

- examples/ag-demo-grails/grails-app/views/org/index.gsp
- examples/ag-demo-grails/grails-app/views/orgShowCase/_form.gsp
- examples/ag-demo-grails/grails-app/views/orgShowCase/_search.gsp
- examples/ag-demo-grails/grails-app/views/orgShowCase/index.gsp
- examples/ag-demo-grails/grails-app/views/orgTabs/index.gsp
- examples/ag-demo-grails/grails-app/views/user/_form.gsp
- examples/ag-demo-grails/grails-app/views/user/_search.gsp
- examples/ag-demo-grails/grails-app/views/user/index.gsp
- examples/demo/mocker/index.js
- examples/demo/src/grids/index.js
- examples/demo/src/grids/list.html
- examples/demo/src/grids/listCtrl.js
- examples/demo/src/grids/restApiGrid/listCtrl.js
- examples/demo/src/grids/simpleDialog.html
- examples/demo/src/grids/templates/searchForm.html
- examples/demo/src/routerStates.js
- examples/demo/webpack.config.js
- package.json
- src/ng/forms/services/FormDialogServ.js
- src/ng/resourceSupport/resourceModule.js
- src/ng/utils/ngHelpers.js
- yarn.lock
Added example for RestApi grid
> Rest api grid example

- grails/ag-plugin/web-app/angleGrinder/scripts/angleGrinder.gridz.min.js
- src/scripts/gridz/directives/agGridXlsExport.coffee
> Fixed xlsx export for strings like 12E-20 rel 9ci/rcm#4913

- examples/ag-demo-grails/grails-app/controllers/agdemo/api/UserController.groovy
- examples/ag-demo-ui/public/templates/org/searchForm.html
- examples/ag-demo-ui/public/templates/user/search.html
- examples/ag-demo-ui/src/org/adminOrgModule.js
- examples/demo/mocker/index.js
- examples/demo/src/forms/select/selFromData/comp.html
- src/ng/components/ag-select-rest/AgSelectRestCtrl.js
- src/ng/components/ag-select-rest/ag-select-rest.comp.html
- src/ng/components/ag-select-rest/ag-select-rest.comp.js
- src/ng/components/index.js
> Ag select rest starting point

- examples/demo/mocker/index.js
- examples/demo/src/components/button/colors-states/component.js
- examples/demo/src/data/selects.js
- examples/demo/src/forms/select-rest/select-rest.html
- examples/demo/src/forms/select-rest/selectRest.js
- examples/demo/src/forms/select/basic/comp.html
- examples/demo/src/forms/select/basic/index.js
- examples/demo/src/forms/select/selFromData/comp.html
- examples/demo/src/forms/select/selFromData/comp.js
- examples/demo/src/forms/select/selFromData/index.js
- examples/demo/src/main.js
- src/ng/components/AgBaseComponent.js
- src/ng/components/ag-select-rest/AgSelectRestCtrl.js
- src/ng/components/ag-select/ag-select2.comp.html
- src/ng/components/ag-select/index.js
- src/ng/select2/ui.select2.js
> 482 select2 fixes

- examples/demo/src/controls/select/basic/comp.html
- src/ng/controls/ag-select/index.js
- src/ng/controls/ui-select2/dataQuery.js
- src/ng/controls/ui-select2/ui.select2.js
- src/ng/legacy/ag-grid/directives/gridCrud.js
> Select displayFields for using different fields #558

- grails/ag-plugin/AngleGrinderGrailsPlugin.groovy
- src/scripts/gridz/directives/agGrid/agGridCtrl.coffee
> 9ci/rcm#5060 Totals fix

- examples/demo/src/app.config.js
- examples/demo/src/controls/xedit-form/xedit1/comp.html
- src/styles/forms/_xeditable.scss
> 593 xedit tweaks
